#
#
#  _____       _                 _____ _        _
# |  __ \     | |               / ____| |      | |
# | |  | | ___| |_   ___  _____| (___ | |_ __ _| |_ ___
# | |  | |/ _ \ | | | \ \/ / _ \\___ \| __/ _` | __/ __|
# | |__| |  __/ | |_| |>  <  __/____) | || (_| | |_\__ \
# |_____/ \___|_|\__,_/_/\_\___|_____/ \__\__,_|\__|___/
#
#
# Author: FusionCoding
# Version: 1.0
# State: ALPHA
#
General:
 Prefix: "&bDeluxe&7Stats \xbb &7"